In [0]:
# Import numpy library

import numpy as np

In [0]:
# Import other useful python libraries

import math
import random

In [0]:
# Check the version of each imported library

print("The vesion of the numpy library: " + np.__version__)

The vesion of the numpy library: 1.16.4


In [0]:
# Check whether numpy library is imported. 
# If library is imported in the current session, then output of below statement should return True

'numpy' in sys.modules

True

In [0]:
# Create a numpy array using a list

n_array = np.array([30,56,23,45,50,67,97,62,85,90])

In [0]:
# Let's check the type of resultant object

type(n_array)

numpy.ndarray

In [0]:
# Print the lenth of the array

print('The length of array is', len(n_array))

The length of array is 10


In [0]:
# Print the n_array 

print('Contents of n_array:', n_array)

Contents of n_array: [30 56 23 45 50 67 97 62 85 90]


In [0]:
# We can access the elements of numpy array using indexing

print('The first element of array is', n_array[0])
print('The third element of array is', n_array[2])

The first element of array is 30
The third element of array is 23


In [0]:
# We can also access the elements of numpy array from end of the array

print('The last element of array is', n_array[-1])
print('The second last element of array is', n_array[-2])

The last element of array is 90
The second last element of array is 85


We can slice the array to extract arrays of the same number of dimensions, but of different sizes than the original. 

Let's look at following examples of slicing the array:

In [0]:
n_array[0:4]  # This will print elements of array with index from 0 to 2, excluding index 3

array([30, 56, 23, 45])

In [0]:
n_array[3:7]

array([45, 50, 67, 97])

In [0]:
n_array[2:]

array([23, 45, 50, 67, 97, 62, 85, 90])

In [0]:
n_array[:4]

array([30, 56, 23, 45])

In [0]:
n_array[:-7]

array([30, 56, 23])

In [0]:
n_array[-7:]

array([45, 50, 67, 97, 62, 85, 90])

In [0]:
n_array[0:9:2]

array([30, 23, 50, 97, 85])

In [0]:
# We can convert numpy array object into list using tolist() function associated with numpy array

n_list = n_array.tolist()

In [0]:
type(n_list)

list

In [0]:
print('Contents of n_list are: ', n_list)

Contents of n_list are:  [30, 56, 23, 45, 50]


In [0]:
# Delete the list named n_list created above

del n_list

Earlier in this tutorial, we imported numpy library and created a numpy array using array() function and passing a list as input to the function.

Let's create an empty numpy array using empty() function. Once created, we will assign the elements to the array by accessing the array using the index.

In [0]:
n = np.empty([10],dtype=int)

In [0]:
for i in range(len(n)):
  n[i] = random.randrange(100,200)

In [0]:
type(n)

numpy.ndarray

In [0]:
print("Contents of array: ", n)

Contents of array:  [189 115 107 173 132 177 199 129 168 149]


In [0]:
for item in range(10):
  print(item,n[item])

0 189
1 115
2 107
3 173
4 132
5 177
6 199
7 129
8 168
9 149


In [0]:
n.min()

103

In [0]:
n.max()

197

In [0]:
n.mean()

157.9

In [0]:
n.dtype

dtype('int64')

In [0]:
n.cumsum()

array([ 117,  312,  476,  644,  818, 1013, 1118, 1279, 1382, 1579])

In [0]:
n.sum()

1579

In [0]:
n.copy()

array([117, 195, 164, 168, 174, 195, 105, 161, 103, 197])

In [0]:
m = n.copy()

In [0]:
print(m)

[117 195 164 168 174 195 105 161 103 197]


In [0]:
n.ndim

1

In [0]:
n.nbytes

80

In [0]:
n.dtype

dtype('int64')

In [0]:
n.shape

(10,)

In [0]:
n = np.append(n,400)

In [0]:
n.nbytes

88

In [0]:
n

array([117, 195, 164, 168, 174, 195, 105, 161, 103, 197, 400])

In [0]:
import sys

In [0]:
import scipy

In [0]:
scipy.

SyntaxError: ignored